version: "3.1"

services:
  node:
    image: nodewithredis
    ports:
      - "3977:3977" # Example port mapping for Node.js application
    depends_on:
      - redis
    environment:
      REDIS_HOST: "0.0.0.0"
      REDIS_PORT: 6379

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
